export const sectionTags = [
  { sectionNumber: "302", tags: ["murder", "kill", "intentional death"] },
  { sectionNumber: "307", tags: ["attempt to murder", "kill attempt"] },
  { sectionNumber: "376", tags: ["rape", "sexual assault", "force", "consent"] },
  { sectionNumber: "375", tags: ["rape definition", "consent", "minor"] },
  { sectionNumber: "498A", tags: ["dowry", "cruelty", "marriage"] },
  { sectionNumber: "304B", tags: ["dowry death", "burns", "injury"] },
  { sectionNumber: "420", tags: ["cheating", "fraud", "dishonest"] },
  { sectionNumber: "354D", tags: ["stalking", "harassment", "cybercrime"] },
  { sectionNumber: "66C", tags: ["identity theft", "fraud", "digital"] },
  { sectionNumber: "20", tags: ["cannabis", "NDPS Act", "drug"] },
  { sectionNumber: "498A", tags: ["dowry", "cruelty", "IPC"] },
  { sectionNumber: "304B", tags: ["dowry death", "IPC"] },
  { sectionNumber: "375", tags: ["rape", "definition", "IPC"] },
  { sectionNumber: "509", tags: ["insult modesty", "IPC"] },
  { sectionNumber: "279", tags: ["rash driving", "MV Act", "IPC"] },
  { sectionNumber: "337", tags: ["hurt", "rash act", "IPC"] },
  { sectionNumber: "338", tags: ["grievous hurt", "rash act", "IPC"] },
  { sectionNumber: "124A", tags: ["sedition", "IPC"] },
  { sectionNumber: "153A", tags: ["enmity", "religion", "IPC"] },
  { sectionNumber: "295A", tags: ["insult religion", "IPC"] },
  { sectionNumber: "326", tags: ["grievous hurt", "weapon", "IPC"] },
  { sectionNumber: "380", tags: ["theft", "dwelling house", "IPC"] },
  { sectionNumber: "394", tags: ["robbery", "hurt", "IPC"] },
  { sectionNumber: "154", tags: ["cognizable case", "information", "CrPC"] },
  { sectionNumber: "41", tags: ["arrest", "warrant", "CrPC"] },
  { sectionNumber: "91", tags: ["summons", "produce document", "CrPC"] },
  { sectionNumber: "160", tags: ["witness attendance", "CrPC"] },
  { sectionNumber: "173", tags: ["police report", "CrPC"] },
  { sectionNumber: "4", tags: ["penetrative sexual assault", "POCSO"] },
  { sectionNumber: "6", tags: ["aggravated sexual assault", "POCSO"] },
  { sectionNumber: "14", tags: ["child porn", "POCSO"] },
  { sectionNumber: "19", tags: ["reporting offences", "POCSO"] },
  { sectionNumber: "66D", tags: ["cheating by personation", "IT Act"] },
  { sectionNumber: "21", tags: ["manufactured drugs", "NDPS Act"] },
  { sectionNumber: "22", tags: ["psychotropic substances", "NDPS Act"] },
  { sectionNumber: "184", tags: ["dangerous driving", "MV Act"] },
  { sectionNumber: "185", tags: ["drunk driving", "MV Act"] },
  { sectionNumber: "3", tags: ["firearms license", "Arms Act"] },
  { sectionNumber: "25", tags: ["firearms offences", "Arms Act"] },
  { sectionNumber: "378", tags: ["theft", "IPC"] },
  { sectionNumber: "379", tags: ["theft punishment", "IPC"] },
  // Add the rest if needed
];
